In [1]:
import pandas as pd

In [2]:
combined_data = pd.read_csv('../../data/combined_for_analysis_sensationalism_jargon_categories_domain_labels.csv')

In [3]:
combined_data.head()

,Unnamed: 0,year,month,title,link_flair_text,domain,score,num_comments,sensationalism_score,jargon_proportion,...,is_top_domain_scientific,is_top_domain_news,is_top_domain_repo,is_top_domain_scam,is_top_domain_unknown,is_top_domain_indecisive,is_top_domain_less_than_2,label_voting_lm,label_voting_manual,top_category
0,0,2018,3,The Bradford pear has created an ecological ni...,Biology,greenvilleonline.com,2,4,0.533427,0.181818,...,False,False,False,False,False,False,False,less_than_2,less_than_2,Life Sciences
1,1,2018,3,Astronomers say they've discovered evidence of...,Astronomy,aftau.org,46,11,0.511129,0.068966,...,False,False,False,False,False,False,False,scientific,scientific,Physical Sciences
2,2,2018,3,The first detection of 21 cm signal from hydro...,Astronomy,news.mit.edu,1,0,0.412405,0.083333,...,False,False,False,False,False,False,False,news,news,Physical Sciences
3,3,2018,3,Universe's First Stars Detected? Get the Facts.,Astronomy,news.nationalgeographic.com,1,1,0.561694,0.000000,...,False,False,False,False,False,False,False,news,news,Physical Sciences
4,4,2018,3,Simple telescope picks up hint of the Universe...,Astronomy,arstechnica.com,3,2,0.492255,0.333333,...,False,False,False,False,False,False,False,news,news,Physical Sciences

In [8]:
# get the title from 50 of the rows in the df. 25 of them should be from high scoring articles and 25 from random articles

high_scoring_articles = combined_data[combined_data['score'] > 100]
high_scoring_articles = high_scoring_articles.sample(n=25)
random_articles = combined_data.sample(n=25)

df = pd.concat([high_scoring_articles, random_articles])
df = df[['title']]

df.to_csv('data/annotation_data.csv', index=False)

In [9]:
df.head()

                                                    title
132944  Solar panels that throw shade on canals are an...
182383  The vast majority of children and adolescents ...
37876   First crossover trial using resistance-trained...
153466  Study finds Earth's core is cooling faster tha...
162758  Gene that enables memories, sense of direction...